#!/usr/bin/env bash

current_dir=$(pwd)

input_file="$current_dir/input.txt"
output_file="$current_dir/output.txt"

file_name="${1:-p1.cpp}"
file_path="$current_dir/$file_name"
g++ $file_path -o prog.exe
./prog.exe < $input_file > $output_file

cat $output_file
