#!/usr/bin/env bash

# Remove packages related to Hyprland.
# (You might have others, or not have some of these)
sudo pacman -R aquamarine hyprland hyprutils
yay -R aquamarine-git hyprland-git hyprutils-git \
    tomlplusplus hyprlang hyprcursor \
    hyprwayland-scanner xcb-util-errors

# Install necessary packages
sudo pacman -S gdb ninja gcc cmake meson libxcb \
     cb-proto xcb-util xcb-util-keysyms libxfixes \
     libx11 libxcomposite xorg-xinput libxrender \
     pixman wayland-protocols cairo pango seatd \
     libxkbcommon xcb-util-wm xorg-xwayland \
     libinput libliftoff libdisplay-info cpio

# Reinstall the packages we removed
yay -S tomlplusplus hyprlang hyprcursor \
    hyprwayland-scanner xcb-util-errors \
    hyprutils-git aquamarine-git

# Clone Hyprland and build it (delete the old Hyprland directory if it's still there)
git clone --recursive https://github.com/hyprwm/Hyprland
cd Hyprland
make all && sudo make install
